// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/32       [336416]
Creator        : gkukec
Date           : Thu May 17 16:25:52 2018
Host           : Linux SpeedyCorrin 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/gkukec/Gasper/github/auger-analysis/dbg/tmva_multiclass
Training events: 4000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+5,5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1                          var1                          var1                          var1                                                            'F'    [-4.05916023254,3.58076572418]
var2                          var2                          var2                          Variable 2                                                      'F'    [-3.68905711174,3.78774046898]
var3                          var3                          var3                          Variable 3                    units                             'F'    [-3.61478614807,4.56402540207]
var4                          var4                          var4                          Variable 4                    units                             'F'    [-4.84856987,5.04116535187]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1", "var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[10][5];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[6][10];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[4][6];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 5; fWeights[0] = new double[5]; 
   fLayerSize[1] = 10; fWeights[1] = new double[10]; 
   fLayerSize[2] = 6; fWeights[2] = new double[6]; 
   fLayerSize[3] = 4; fWeights[3] = new double[4]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.578479892742958;
   fWeightMatrix0to1[1][0] = 1.8190637034073;
   fWeightMatrix0to1[2][0] = -0.456592650729437;
   fWeightMatrix0to1[3][0] = -1.10409091652716;
   fWeightMatrix0to1[4][0] = -1.2789041690697;
   fWeightMatrix0to1[5][0] = -0.225778241090232;
   fWeightMatrix0to1[6][0] = -0.108645370879605;
   fWeightMatrix0to1[7][0] = -0.415185931509869;
   fWeightMatrix0to1[8][0] = -0.550248712513835;
   fWeightMatrix0to1[0][1] = 0.0885311420198543;
   fWeightMatrix0to1[1][1] = 0.98246539162424;
   fWeightMatrix0to1[2][1] = -0.0894201566583469;
   fWeightMatrix0to1[3][1] = -0.708070285963457;
   fWeightMatrix0to1[4][1] = -0.80509862505762;
   fWeightMatrix0to1[5][1] = -0.164130321913898;
   fWeightMatrix0to1[6][1] = 0.405276404790424;
   fWeightMatrix0to1[7][1] = -2.17514623217672;
   fWeightMatrix0to1[8][1] = 2.83363319512583;
   fWeightMatrix0to1[0][2] = 0.406906425695475;
   fWeightMatrix0to1[1][2] = 0.924362729524714;
   fWeightMatrix0to1[2][2] = -0.0299974937176769;
   fWeightMatrix0to1[3][2] = -1.52480113646217;
   fWeightMatrix0to1[4][2] = -0.141336282632718;
   fWeightMatrix0to1[5][2] = 1.49218282675067;
   fWeightMatrix0to1[6][2] = -1.17885713727561;
   fWeightMatrix0to1[7][2] = -0.085529288717747;
   fWeightMatrix0to1[8][2] = -0.152629106572285;
   fWeightMatrix0to1[0][3] = -0.171333627284904;
   fWeightMatrix0to1[1][3] = -3.27284645235091;
   fWeightMatrix0to1[2][3] = -0.376325634055712;
   fWeightMatrix0to1[3][3] = 2.57197135426596;
   fWeightMatrix0to1[4][3] = 1.75311329770872;
   fWeightMatrix0to1[5][3] = -1.02482673844816;
   fWeightMatrix0to1[6][3] = 0.935792388502625;
   fWeightMatrix0to1[7][3] = -0.135741028957685;
   fWeightMatrix0to1[8][3] = 0.0620467583636353;
   fWeightMatrix0to1[0][4] = -2.35990139026348;
   fWeightMatrix0to1[1][4] = 0.272351132769221;
   fWeightMatrix0to1[2][4] = 0.0421273268192183;
   fWeightMatrix0to1[3][4] = 2.08528091679817;
   fWeightMatrix0to1[4][4] = 2.49668040386753;
   fWeightMatrix0to1[5][4] = 2.68188788086468;
   fWeightMatrix0to1[6][4] = 1.21795248327311;
   fWeightMatrix0to1[7][4] = 3.91317992558998;
   fWeightMatrix0to1[8][4] = -3.21735369369143;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -2.54035263248796;
   fWeightMatrix1to2[1][0] = 1.78889679759122;
   fWeightMatrix1to2[2][0] = -0.995782792223451;
   fWeightMatrix1to2[3][0] = 0.507823854577415;
   fWeightMatrix1to2[4][0] = 1.63445107767562;
   fWeightMatrix1to2[0][1] = 1.08675490706425;
   fWeightMatrix1to2[1][1] = 0.185440701337288;
   fWeightMatrix1to2[2][1] = 0.108101955306355;
   fWeightMatrix1to2[3][1] = -0.335290440321749;
   fWeightMatrix1to2[4][1] = -1.34592428208375;
   fWeightMatrix1to2[0][2] = -0.276873530384768;
   fWeightMatrix1to2[1][2] = -0.737937274306216;
   fWeightMatrix1to2[2][2] = -0.478556172481835;
   fWeightMatrix1to2[3][2] = 1.70707756185246;
   fWeightMatrix1to2[4][2] = 0.212586316968107;
   fWeightMatrix1to2[0][3] = -1.28820768933778;
   fWeightMatrix1to2[1][3] = 0.401809539592624;
   fWeightMatrix1to2[2][3] = -2.3236413634569;
   fWeightMatrix1to2[3][3] = -0.746946173919372;
   fWeightMatrix1to2[4][3] = 0.863396600771977;
   fWeightMatrix1to2[0][4] = 0.976749184371197;
   fWeightMatrix1to2[1][4] = -0.0971524121569913;
   fWeightMatrix1to2[2][4] = -0.86872950902079;
   fWeightMatrix1to2[3][4] = 2.26044376815014;
   fWeightMatrix1to2[4][4] = 0.392446718711901;
   fWeightMatrix1to2[0][5] = 0.419897045881435;
   fWeightMatrix1to2[1][5] = -1.7154868661712;
   fWeightMatrix1to2[2][5] = -1.36855093369275;
   fWeightMatrix1to2[3][5] = 1.89742962268065;
   fWeightMatrix1to2[4][5] = 1.32552769406153;
   fWeightMatrix1to2[0][6] = 0.734841102404815;
   fWeightMatrix1to2[1][6] = -2.01968714368378;
   fWeightMatrix1to2[2][6] = -0.553833279087288;
   fWeightMatrix1to2[3][6] = 0.803918828231044;
   fWeightMatrix1to2[4][6] = 0.030060218132844;
   fWeightMatrix1to2[0][7] = 1.02472590644563;
   fWeightMatrix1to2[1][7] = 0.193244180710912;
   fWeightMatrix1to2[2][7] = 1.207858087019;
   fWeightMatrix1to2[3][7] = -2.66361622433643;
   fWeightMatrix1to2[4][7] = -0.954691882921004;
   fWeightMatrix1to2[0][8] = 0.179608207533417;
   fWeightMatrix1to2[1][8] = 0.589140897027194;
   fWeightMatrix1to2[2][8] = 0.957050435440423;
   fWeightMatrix1to2[3][8] = -1.8215136979259;
   fWeightMatrix1to2[4][8] = -0.842831393247091;
   fWeightMatrix1to2[0][9] = 0.936629239294096;
   fWeightMatrix1to2[1][9] = -1.33669531015164;
   fWeightMatrix1to2[2][9] = 2.79762382519013;
   fWeightMatrix1to2[3][9] = -0.728982534432252;
   fWeightMatrix1to2[4][9] = -1.24982314816709;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.860815440975422;
   fWeightMatrix2to3[1][0] = -0.200600029451094;
   fWeightMatrix2to3[2][0] = -0.325104823565836;
   fWeightMatrix2to3[3][0] = -0.491362545953542;
   fWeightMatrix2to3[0][1] = 0.801960252206232;
   fWeightMatrix2to3[1][1] = -0.650118667914315;
   fWeightMatrix2to3[2][1] = -1.03986463360686;
   fWeightMatrix2to3[3][1] = 0.180647908125783;
   fWeightMatrix2to3[0][2] = 0.0121365958190375;
   fWeightMatrix2to3[1][2] = -0.501968865309146;
   fWeightMatrix2to3[2][2] = 0.497362045211822;
   fWeightMatrix2to3[3][2] = -0.00743695689362747;
   fWeightMatrix2to3[0][3] = 0.0139329160623453;
   fWeightMatrix2to3[1][3] = 0.0505976156757792;
   fWeightMatrix2to3[2][3] = 0.464727127398656;
   fWeightMatrix2to3[3][3] = -0.529711256391173;
   fWeightMatrix2to3[0][4] = 0.571697306997735;
   fWeightMatrix2to3[1][4] = -0.543019564316845;
   fWeightMatrix2to3[2][4] = -0.0272790719595521;
   fWeightMatrix2to3[3][4] = -0.00158531794615864;
   fWeightMatrix2to3[0][5] = 0.488883279826055;
   fWeightMatrix2to3[1][5] = -0.460225094210958;
   fWeightMatrix2to3[2][5] = -0.755054021651661;
   fWeightMatrix2to3[3][5] = 1.17552285503144;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
